import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg, paddingBottom: 60, flexGrow: 1, justifyContent: 'center' },

  // Role picker (Login screen)
  heading: { fontSize: 20, fontWeight: '800', color: colors.text, textAlign: 'center' },
  subheading: { fontSize: 13, color: colors.textMuted, textAlign: 'center', marginTop: 6, marginBottom: spacing.xl },
  roleCard: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing.lg,
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  roleIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  roleTitle: { fontSize: 15, fontWeight: '700', color: colors.text },
  roleSubtitle: { fontSize: 12, color: colors.textMuted, textAlign: 'center', marginTop: 4 },
  footerLinkRow: { flexDirection: 'row', justifyContent: 'center', marginTop: spacing.md },
  footerText: { fontSize: 13, color: colors.textMuted },
  footerLink: { fontSize: 13, color: colors.primary, fontWeight: '700' },

  // Login/Register forms
  formCard: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing.lg,
  },
  formIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  formTitle: { fontSize: 18, fontWeight: '800', color: colors.text },
  formSubtitle: { fontSize: 12, color: colors.textMuted, marginTop: 4, marginBottom: spacing.lg },

  segmentRow: { flexDirection: 'row', marginBottom: spacing.lg },
  segmentBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  segmentBtnLeft: { marginRight: spacing.sm },
  segmentBtnRight: {},
  segmentBtnActive: { backgroundColor: '#DBEAFE', borderColor: colors.primary },
  segmentText: { fontSize: 13, fontWeight: '600', color: colors.text },
  segmentTextActive: { color: colors.primary },

  field: { marginBottom: spacing.md },
  label: { fontSize: 13, fontWeight: '600', color: colors.text, marginBottom: spacing.xs },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.white,
  },
  passwordRow: { flexDirection: 'row', alignItems: 'center' },
  passwordInput: { flex: 1 },
  eyeBtn: { position: 'absolute', right: 12 },
  helperText: { fontSize: 11, color: colors.textMuted, marginTop: 4 },

  forgotLink: { alignSelf: 'flex-end', marginBottom: spacing.md },
  forgotLinkText: { fontSize: 12, color: colors.primary, fontWeight: '600' },

  primaryBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  primaryBtnText: { color: colors.white, fontWeight: '700', fontSize: 15 },

  dividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: spacing.lg },
  dividerLine: { flex: 1, height: 1, backgroundColor: colors.border },
  dividerText: { fontSize: 11, color: colors.textMuted, marginHorizontal: spacing.sm },

  socialRow: { flexDirection: 'row', marginBottom: spacing.sm },
  socialBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: 10,
    marginRight: 8,
  },
  socialBtnText: { fontSize: 12, fontWeight: '600', color: colors.text, marginLeft: 6 },
  googleBtn: { marginBottom: spacing.md },

  switchRoleText: { fontSize: 13, color: colors.textMuted, textAlign: 'center', marginTop: 4 },
  switchRoleLink: { color: colors.primary, fontWeight: '700' },

  // "Login required" modal
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
  modalBody: { padding: spacing.xl, alignItems: 'center' },
  modalIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  modalMessage: { fontSize: 13, color: colors.textMuted, textAlign: 'center', marginBottom: spacing.lg },
  modalBtnRow: { flexDirection: 'row', width: '100%' },
  modalPrimaryBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 12,
    alignItems: 'center',
    marginRight: 8,
  },
  modalPrimaryBtnText: { color: colors.white, fontWeight: '700', fontSize: 13 },
  modalSecondaryBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalSecondaryBtnText: { color: colors.text, fontWeight: '700', fontSize: 13 },
});
