import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  authStatusRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.lg },
  authStatusText: { fontSize: 12, color: colors.textMuted, marginLeft: 6, fontWeight: '600' },
  title: { fontSize: 24, fontWeight: '800', color: colors.text },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.md,
  },
  editBtnText: { color: colors.white, fontWeight: '700', fontSize: 13, marginLeft: 6 },
  alert: {
    borderLeftWidth: 4,
    borderLeftColor: colors.accent,
    backgroundColor: '#FFFBEB',
    padding: spacing.md,
    borderRadius: radius.sm,
    marginBottom: spacing.lg,
  },
  alertText: { color: '#78350F', fontSize: 13, lineHeight: 18 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  statCard: { width: '48%' },
  statLabel: { fontSize: 12, color: colors.textMuted, marginBottom: 6 },
  statValue: { fontSize: 20, fontWeight: '800', color: colors.text },
  statSub: { fontSize: 12, fontWeight: '400', color: colors.textMuted },
  badge: {
    backgroundColor: '#F3F4F6',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.full,
    marginTop: 4,
  },
  badgeText: { fontSize: 12, color: colors.textMuted, fontWeight: '600' },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: spacing.sm },
  summaryText: { color: colors.textMuted, fontSize: 14, lineHeight: 20 },
  viewProfileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
  },
  viewProfileText: { color: colors.primary, fontWeight: '700', marginRight: 6 },

  brandBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: spacing.md,
    marginBottom: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  brandLogoRow: { flexDirection: 'row', alignItems: 'center' },
  hamburgerBtn: { marginRight: spacing.sm },
  brandLogoImage: {
    width: 36,
    height: 36,
    marginRight: spacing.sm,
  },
  brandName: { fontSize: 16, fontWeight: '800', color: colors.text },
  brandTagline: { fontSize: 8, fontWeight: '700', color: colors.textMuted, letterSpacing: 0.3, marginTop: 1 },
  brandNavLink: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    textDecorationLine: 'underline',
  },

  starRow: { flexDirection: 'row', marginBottom: 6 },
  starIcon: { marginRight: 2 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalBackdropPress: { ...StyleSheet.absoluteFillObject },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.lg,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  modalTitle: { fontSize: 17, fontWeight: '800', color: colors.text, flex: 1, marginRight: spacing.sm },
  modalBody: { fontSize: 13, color: colors.textMuted, lineHeight: 19, marginBottom: spacing.lg },
  modalLabel: { fontSize: 12, fontWeight: '700', color: colors.text, marginBottom: 6 },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.text,
    marginBottom: spacing.lg,
  },
  modalSaveBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  modalSaveBtnText: { color: colors.white, fontWeight: '700', fontSize: 14 },
  modalSkipText: { color: colors.textMuted, fontSize: 13, textAlign: 'center', textDecorationLine: 'underline' },
});
