import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg, paddingBottom: 60 },
  pageTitle: { fontSize: 20, fontWeight: '800', color: colors.text, marginBottom: 4 },
  pageSubtitle: { fontSize: 12, color: colors.textMuted, marginBottom: spacing.lg },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: colors.text, marginBottom: spacing.md },

  // Photo & Resume
  photoRow: { flexDirection: 'row', alignItems: 'center' },
  avatarTouchable: { marginRight: 10 },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  avatarText: { color: colors.white, fontWeight: '700', fontSize: 16 },
  photoButtonsWrap: { flexDirection: 'row', flexShrink: 1 },
  resumeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  resumeStatusText: { fontSize: 13, color: colors.textMuted, marginRight: 10, flexShrink: 1 },
  requiredText: { fontSize: 12, color: colors.danger, fontWeight: '600', marginLeft: 10 },
  pillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.full,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  pillBtnActive: { backgroundColor: '#ECFDF5', borderColor: colors.success },
  pillBtnText: { fontSize: 12, fontWeight: '600', color: colors.text, marginLeft: 6 },
  pillBtnTextActive: { color: colors.success },

  // Generic fields
  field: { marginBottom: spacing.lg },
  label: { fontSize: 13, fontWeight: '600', color: colors.text, marginBottom: spacing.xs },
  required: { color: colors.danger },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.white,
  },
  textArea: { minHeight: 90, textAlignVertical: 'top' },
  error: { color: colors.danger, fontSize: 12, marginTop: 4 },
  row: { flexDirection: 'row' },
  rowItem: { flex: 1, marginRight: 8 },
  pickerBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    overflow: 'hidden',
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  switchLabel: { fontSize: 14, color: colors.text, fontWeight: '600' },
  saveBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  saveBtnText: { color: colors.white, fontWeight: '700', fontSize: 15 },
});
