import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export default StyleSheet.create({
  card: {
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.md,
    overflow: 'hidden',
  },
  inner: { padding: spacing.md },
  topRow: { flexDirection: 'row', alignItems: 'flex-start' },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  avatarText: { color: colors.white, fontWeight: '700', fontSize: 16 },
  nameBlock: { flex: 1 },
  name: { fontSize: 15, fontWeight: '700', color: colors.text },
  role: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  location: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  metaCol: { alignItems: 'flex-end' },
  availableBadge: { flexDirection: 'row', alignItems: 'center' },
  availableDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.success, marginRight: 4 },
  availableText: { fontSize: 11, color: colors.success, fontWeight: '600' },
  postedAgo: { fontSize: 10, color: colors.textMuted, marginTop: 4 },
  skillsWrap: { flexDirection: 'row', flexWrap: 'wrap', marginTop: spacing.sm },
  skillChip: {
    backgroundColor: '#EFF6FF',
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginRight: 6,
    marginBottom: 6,
  },
  skillChipText: { color: colors.primaryDark, fontSize: 10, fontWeight: '700' },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  rate: { fontSize: 15, fontWeight: '800', color: colors.text },
  viewBtn: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  viewBtnText: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  ratingRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  ratingText: { fontSize: 11, color: colors.textMuted, marginLeft: 4 },
  lockBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EFF6FF',
    paddingVertical: 8,
  },
  lockText: { fontSize: 11, color: colors.primaryDark, fontWeight: '600', marginLeft: 6 },
});
