import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export default StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.sm,
  },
  card: {
    width: '100%',
    maxHeight: '92%',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    overflow: 'hidden',
  },

  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  brandRow: { flexDirection: 'row', alignItems: 'center' },
  brandBadge: {
    width: 26,
    height: 26,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  brandBadgeText: { color: colors.white, fontWeight: '800', fontSize: 13 },
  brandName: { fontSize: 13, fontWeight: '700', color: colors.text },
  topBarRight: { flexDirection: 'row', alignItems: 'center' },
  topBarIconBtn: { marginLeft: spacing.md },

  priceSummary: {
    backgroundColor: colors.primaryDark,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  priceSummaryLabel: { fontSize: 11, color: 'rgba(255,255,255,0.7)', fontWeight: '600' },
  priceSummaryAmount: { fontSize: 24, fontWeight: '800', color: colors.white, marginTop: 2 },
  usingAsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    marginTop: spacing.md,
  },
  usingAsText: { fontSize: 12, color: colors.white, marginLeft: 8, flex: 1 },

  methodTabsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  methodTab: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  methodTabActive: { borderBottomColor: colors.primary },
  methodTabText: { fontSize: 12, fontWeight: '600', color: colors.textMuted },
  methodTabTextActive: { color: colors.primary },

  methodContent: { padding: spacing.lg, minHeight: 220 },
  methodTitle: { fontSize: 13, fontWeight: '700', color: colors.text, marginBottom: spacing.md },

  // UPI
  qrBox: {
    width: 140,
    height: 140,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9FAFB',
    marginBottom: spacing.md,
  },
  qrHelperText: { fontSize: 12, color: colors.textMuted, textAlign: 'center' },

  // Cards form
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.text,
    marginBottom: spacing.md,
  },
  inputRow: { flexDirection: 'row' },
  inputHalf: { flex: 1, marginRight: 8 },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.lg },
  checkboxText: { fontSize: 12, color: colors.textMuted, marginLeft: 8, flex: 1 },
  continueBtn: {
    backgroundColor: colors.text,
    borderRadius: radius.md,
    paddingVertical: 13,
    alignItems: 'center',
  },
  continueBtnText: { color: colors.white, fontWeight: '700', fontSize: 14 },

  // List rows (EMI / Netbanking / Wallet / Pay Later)
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
  },
  searchInput: { flex: 1, paddingVertical: 10, marginLeft: 8, fontSize: 14, color: colors.text },
  listGroupLabel: { fontSize: 11, fontWeight: '700', color: colors.textMuted, marginBottom: spacing.sm, marginTop: spacing.sm },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  optionIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  optionLabel: { fontSize: 13, color: colors.text, fontWeight: '600', flex: 1 },
  optionSubLabel: { fontSize: 11, color: colors.textMuted, marginTop: 1 },

  footer: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  footerText: { fontSize: 11, color: colors.textMuted },

  // Exit confirmation
  exitBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  exitCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.xl,
    alignItems: 'center',
  },
  exitIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  exitTitle: { fontSize: 15, fontWeight: '700', color: colors.text, textAlign: 'center' },
  exitSubtitle: { fontSize: 12, color: colors.textMuted, textAlign: 'center', marginTop: 4, marginBottom: spacing.lg },
  exitContinueBtn: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  exitContinueBtnText: { fontSize: 14, fontWeight: '700', color: colors.text },
  exitConfirmBtn: {
    width: '100%',
    backgroundColor: colors.text,
    borderRadius: radius.md,
    paddingVertical: 12,
    alignItems: 'center',
  },
  exitConfirmBtnText: { fontSize: 14, fontWeight: '700', color: colors.white },
});
